on: workflow_dispatch

jobs:
  create-pr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: create pr of cherry-pick
        run: |
          base_pr_branch="cherrybot-${RANDOM}"
          git config user.name github-actions
          git config user.email github-actions@github.com
          git fetch
          git switch -c $base_pr_branch
          git remote add other $OTHER_REPO_FULL.git -f --no-tags -t main -m main
          
          commit_hash="$(git rev-parse refs/remotes/other/HEAD)"
          
          git cherry-pick $commit_hash --strategy-option theirs
          git push --set-upstream origin $base_pr_branch

          commit_msg="$(git show -s --format=%s)"
          echo "commit msg is $commit_msg"
          
          title_txt="$(sed -E 's/ \(#[0-9]+\)$//' <<< $commit_msg)"
          echo "title text is $title_txt"

          remote_pr_id=$(gawk 'match($0, /\(#([0-9]+)\)$/, ary) {print ary[1]}' <<< $commit_msg)
          remote_pr_body="$(gh pr view $remote_pr_id --repo $OTHER_REPO_FULL.git --json body --jq '.body')"  

          body_text="This is an automatic cherry-pick of [$commit_hash]($OTHER_REPO_FULL/commit/$commit_hash)
          
          The original PR was [#$remote_pr_id]($OTHER_REPO_FULL/pull/$emote_pr_id) with message:

          $remote_pr_body"
          echo "body text is $body_text"
          gh pr create --title "$title_txt" --body "$body_text" --base main --repo $THIS_REPO
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          THIS_REPO: "madelen-at-work/action-tester2"
          OTHER_REPO_FULL: "https://github.com/madelen-at-work/action-tester"
