on: workflow_dispatch

jobs:
  print:
    runs-on: ubuntu-latest
    steps:
      - name: Print to log
        run: echo "hello log"
  do-da-pr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: clone 2nd repo
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git fetch
          git switch -c $BASE_PR_BRANCH
          git remote add other $OTHER_REPO -f --no-tags -t main -m main
          
          git cherry-pick refs/remotes/other/HEAD --strategy-option theirs
          git push --set-upstream origin $BASE_PR_BRANCH
          title_text=$(git show -s --format=%s)
          body_text="Cherry-pick from $OTHER_REPO_FULL"
          gh pr create --title $title_text --body $body_text --base main --repo $THIS_REPO
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          THIS_REPO: "madelen-at-work/action-tester2"
          OTHER_REPO_FULL: "https://github.com/madelen-at-work/action-tester.git"
          BASE_PR_BRANCH: "cherrybot/github-actions/action/${RANDOM}"
