on: workflow_dispatch
#  push:
#    branches:
#      - 'main'

jobs:
  print:
    runs-on: ubuntu-latest
    steps:
      - name: Print to log
        run: echo "hello log"
  do-da-pr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: clone 2nd repo
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git fetch
          git switch -c "pr-branch"
          git remote add other https://github.com/madelen-at-work/action-tester.git -F --no-tags -t main -m main
          
          git cherry-pick refs/remotes/other/HEAD --strategy-option theirs
          git push --set-upstream origin pr-branch
          gh pr create --title "test pr from gh" --body "Could this work?" --base main --repo madelen-at-work/action-tester2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
